version: '3.8'

services: 
  neo4j-db: 
    container_name: neo4j-db
    image: neo4j:5.11.0-enterprise
    ports: 
      - 7474:7474
      - 7687:7687
    restart: 'always'
    environment:
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_server_bolt_enabled=true
      - NEO4J_server_bolt_tls__level=DISABLED
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_http_enabled=true
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_initial_dbms_default__database=neo4j
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_backup_listen__address=0.0.0.0:6362
      - NEO4J_server_backup_enabled=true
      - NEO4J_AUTH=neo4j/<YOUR PASSWORD DB>
    volumes:
      - ./data:/data

  neo4j-backup:
    container_name: neo4j-backup
    ports: 
      - 22:22
    environment:
      - ROOT_PASSWORD=<YOUR_PASSWORD_UBUNTU>
    depends_on:
      - neo4j-db
    build:
      context: ./
      dockerfile: Dockerfile
    
    
